name: neuralera_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  device_preview: ^1.2.0
  flutter_native_splash: ^2.4.6
  google_sign_in: ^6.3.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - img/logo.png
